function scenario = load_pid_scenario(csv_path)
%LOAD_PID_SCENARIO Read PID-generated scenario CSV exported by the web UI.
%   scenario = LOAD_PID_SCENARIO(csv_path)
%
%   Input:
%     csv_path : CSV file path exported from "pid工况仿真导出器.html"
%
%   Output:
%     scenario : struct with grouped fields for later prediction / replay
%
%   Usage example:
%     scenario = load_pid_scenario('pid_scenario_20260529_012300.csv');
%     t = scenario.time_s;
%     alpha_rad = scenario.inputs.alpha_rad;
%     phi_rad = scenario.inputs.phi_rad;
%     xT_m = scenario.points.T(:, 1);
%
%   If csv_path is omitted, a file picker will be shown.

    if nargin < 1 || isempty(csv_path)
        [file_name, folder_path] = uigetfile('*.csv', '选择 PID 工况 CSV 文件');
        if isequal(file_name, 0)
            error('load_pid_scenario:NoFileSelected', '未选择 CSV 文件。');
        end
        csv_path = fullfile(folder_path, file_name);
    end

    table_data = readtable(csv_path);
    required_cols = {
        'time_s', 'dt_s', 'v_input_mps', ...
        'l_m', 'l_h_m', 'L_m', 'width_m', ...
        'theta_ref_rad', 'theta_ref_deg', ...
        'theta_rad', 'theta_deg', ...
        'theta_t_rad', 'theta_t_deg', ...
        'alpha_rad', 'alpha_deg', ...
        'phi_rad', 'phi_deg', ...
        'xA_m', 'yA_m', 'xB_m', 'yB_m', ...
        'xH_m', 'yH_m', 'xT_m', 'yT_m'
    };

    missing_cols = required_cols(~ismember(required_cols, table_data.Properties.VariableNames));
    if ~isempty(missing_cols)
        error( ...
            'load_pid_scenario:MissingColumns', ...
            'CSV 缺少必要字段: %s', ...
            strjoin(missing_cols, ', ') ...
        );
    end

    scenario = struct();
    scenario.csv_path = string(csv_path);
    scenario.file_name = string(local_basename(csv_path));
    scenario.table = table_data;
    scenario.row_count = height(table_data);

    scenario.time_s = table_data.time_s;
    scenario.dt_s = table_data.dt_s(1);

    scenario.params = struct( ...
        'l_m', table_data.l_m(1), ...
        'l_h_m', table_data.l_h_m(1), ...
        'L_m', table_data.L_m(1), ...
        'width_m', table_data.width_m(1) ...
    );

    scenario.inputs = struct( ...
        'v_mps', table_data.v_input_mps, ...
        'alpha_rad', table_data.alpha_rad, ...
        'alpha_deg', table_data.alpha_deg, ...
        'phi_rad', table_data.phi_rad, ...
        'phi_deg', table_data.phi_deg, ...
        'theta_ref_rad', table_data.theta_ref_rad, ...
        'theta_ref_deg', table_data.theta_ref_deg ...
    );

    scenario.states = struct( ...
        'theta_rad', table_data.theta_rad, ...
        'theta_deg', table_data.theta_deg, ...
        'theta_t_rad', table_data.theta_t_rad, ...
        'theta_t_deg', table_data.theta_t_deg, ...
        'xB_m', table_data.xB_m, ...
        'yB_m', table_data.yB_m ...
    );

    scenario.points = struct( ...
        'A', [table_data.xA_m, table_data.yA_m], ...
        'B', [table_data.xB_m, table_data.yB_m], ...
        'H', [table_data.xH_m, table_data.yH_m], ...
        'T', [table_data.xT_m, table_data.yT_m] ...
    );

    scenario.summary = struct( ...
        't_start_s', table_data.time_s(1), ...
        't_end_s', table_data.time_s(end), ...
        'duration_s', table_data.time_s(end) - table_data.time_s(1), ...
        'sample_count', height(table_data), ...
        'max_abs_alpha_deg', max(abs(table_data.alpha_deg)), ...
        'max_abs_phi_deg', max(abs(table_data.phi_deg)), ...
        'tail_end_x_m', table_data.xT_m(end), ...
        'tail_end_y_m', table_data.yT_m(end) ...
    );
end

function name = local_basename(file_path)
    [~, name_only, ext] = fileparts(file_path);
    name = [name_only, ext];
end
